force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Leave Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_c__c/Staff_c__c.object-meta.xml
<CustomObject>
    <label>Staff_c</label>
    <nameField>
        <label>Staff_c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>staffs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_c__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StaffDashboardController.cls
//with sharing enforces record-level access, while without sharing ignores sharing rules.
public with sharing class StaffDashboardController {

    //@AuraEnabled ->This exposes the method to the frontend. without this LWC ❌ cannot call method
    @AuraEnabled(cacheable=true)
    public static Integer getTotalStaff() {
        return [SELECT COUNT()
                FROM Staff_c__c];
    }


    // cacheable=true ->Data can be cached because method only reads data.
    //Required for: * @wire, *Better performance
    @AuraEnabled(cacheable=true)
    //LWC calls methods statically.
    public static Integer getActiveStaff() {
        return [
            SELECT COUNT()
            FROM Staff_c__c
            WHERE Status__c = 'Active'
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Integer getPendingLeaves() {
        return [
            SELECT COUNT()
            FROM Leave_Request__c
            WHERE Status__c = 'Pending Approval'
        ];
    }
}